routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| LaravelLocalization
|--------------------------------------------------------------------------
|
*/

Route::group([
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
function () {


	    Route::get('/', 'HomeController@index')->name('index');
        Route::get('search', 'SearchController@search')->name('search');
        Route::group(['middleware' => ['isVerified']], function () {
        	Route::get('email-verification/error', 'Auth\RegisterController@getVerificationError')->name('email-verification.error');
        	Route::get('email-verification/check/{token}', 'Auth\RegisterController@getVerification')->name('email-verification.check');
        });
        /*
        |--------------------------------------------------------------------------
        | Auth Routes
        |--------------------------------------------------------------------------
        |
        */
	    Auth::routes();
        /*
        |--------------------------------------------------------------------------
        | missing RETURN 404 PAGE Route
        |--------------------------------------------------------------------------
        |
        */
        Route::get('missing', function () {
        	return view('404');
        });
        /*
        |--------------------------------------------------------------------------
        | resource
        |--------------------------------------------------------------------------
        |
        */
		Route::resource('Cat','Categoriass');
		Route::get('/Peliculas/{slug}','Categoriass@ShowPelicula');
        Route::resource('Peliculass','Peliculas');
	     /**
	     * Show the middleware dashboard Super-Admin.
	     *
	     * @return \Illuminate\Contracts\Support\Renderable
	     */
	     Route::group(['middleware' => ['auth','role:Super-Admin']], function () {

		    /*
			|--------------------------------------------------------------------------
			| Web Routes Dashboard
			|--------------------------------------------------------------------------
			|
			| Here is where you can register web routes for your application. These
			| routes are loaded by the RouteServiceProvider within a group which
			| contains the "web" middleware group. Now create something great!
			|
			*/

		


			Route::resource('admin','Dashboard\Dashboard');
			Route::resource('Dashboard/Roles','Dashboard\Roles');
			Route::resource('Dashboard/Users','Dashboard\Users');
			Route::resource('Dashboard/AdSense','Dashboard\AdSenses');
			
			Route::resource('Dashboard/Clients','Dashboard\Clients');
			Route::resource('Dashboard/Galleries','Dashboard\Galleries');
			Route::resource('Dashboard/Instagrams','Dashboard\Instagrams');
			Route::resource('Dashboard/Links','Dashboard\Links');
			Route::resource('Dashboard/Menus','Dashboard\Menus');
			Route::resource('Dashboard/Media','Dashboard\Media');
			Route::resource('Dashboard/Messages','Dashboard\Messages');
			Route::resource('Dashboard/Posts','Dashboard\Posts');
			Route::resource('Dashboard/Seo','Dashboard\Seo');
			Route::resource('Dashboard/Settings','Dashboard\Settings');

		    });


});
Route::group(['middleware' => ['auth','role:Super-Admin']], function () {
Route::get('Dashboard/image/upload','ImageUploadController@fileCreate');
Route::post('Dashboard/image/upload/store','ImageUploadController@fileStore');
Route::post('Dashboard/image/delete','ImageUploadController@fileDestroy');
});

app/Instagram.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\ImageUpload;

class Instagram extends Model
{
     /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [

     'Title_ar','Title_en','Title_fr','body_ar','body_en','body_fr','ImageUpload_id'
     
    ];


    public function ImageUpload()
    {
        return $this->belongsTo(ImageUpload::class,'ImageUpload_id');
    }
}
  

app/Http/Controllers/Dashboard/AdSenses.php
<?php
namespace App\Http\Controllers\Dashboard;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreAdSense;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User; 
use App\AdSense;
use Auth; 
use File;
use Validator; 

class AdSenses extends Controller
{


    /**
     * Show the middleware dashboard Super-Admin.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function __construct()
    {
        $this->middleware(['auth','role_or_permission:Super-Admin|edit articles']);
    }
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          // GET AdSenses
          $AdSenses = AdSense::simplePaginate(5);
          return view('Dashboard.AdSense.index',compact('AdSenses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // GET AdSense create
        return view('Dashboard.AdSense.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
        'Location' => 'required|max:255',
        'name' => 'required|max:30',
        'Display' => 'required|max:30',
        'url' =>'required|unique:ad_senses|max:30',
        'code' => 'required|unique:ad_senses|max:200',
        ]);
        AdSense::create([
            'Location' => $request->Location,  
            'name' => $request->name,   
            'Display' => $request->Display,  
            'Type' => $request->Type, 
            'Active' => $request->Active, 
            'url' => $request->url,
            'code' => $request->code
        ]);
        return redirect()->route('AdSense.index')

                        ->with('success','AdSense Store successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $name
     * @return \Illuminate\Http\Response
     */
    public function edit($name)
    {
        //To Get AdSense 
        $AdSense = AdSense::where('name', '=', $name)->firstOrFail();
        return view('Dashboard.AdSense.edit',compact('AdSense'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $name)
    {
        // GET AdSense
        $AdSense = AdSense::where('name', '=', $name)->firstOrFail();
        // GET validate
        $data = $request->validate([
        'Location' => 'required|max:255',
        'name' => 'required|max:30',
        'Display' => 'required|max:30',
        'url' =>'required|unique:ad_senses|max:30',
        'code' => 'required|unique:ad_senses|max:200',
        ]);
        $AdSense->Location  = $request->input('Location');
        $AdSense->name = $request->input('name');
        $AdSense->Display = $request->input('Display');
        $AdSense->Type = $request->input('Type');
        $AdSense->Active = $request->input('Active');
        $AdSense->url = $request->input('url');
        $AdSense->code = $request->input('code');
        $AdSense->save();
        return redirect()->route('AdSense.index')

                        ->with('success','AdSense Updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         // AdSense AdSense
        $AdSense = AdSense::findOrFail($id);
        $AdSense->delete();
        return back()->with('Delete','AdSense deleted successfully');
    }
}

app/Http/Controllers/Dashboard/Categories.php
<?php

namespace App\Http\Controllers\Dashboard;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCategorias;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User; 
use App\Categorias;
use Auth;
use File;
use Validator;  
  
class Categories extends Controller
{


    /**
     * Show the middleware dashboard Super-Admin.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function __construct()
    {
        $this->middleware(['auth','role_or_permission:Super-Admin|edit articles']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          // GET Categories
          $Categories = Categorias::simplePaginate(5);
          return view('Dashboard.Categories.index',compact('Categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // GET Categories create
        return view('Dashboard.Categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
        'parent_id' => 'required|max:255',
        'order' => 'required',
        'Title_ar' => 'required',
        'Title_en' => 'required',
        'Title_fr' => 'required',
        'color' => 'required',
        ]);

        Categorias::create([
            'parent_id' => $request->parent_id,  
            'order' => $request->order,   
            'Title_ar' => $request->Title_ar,  
            'Title_en' => $request->Title_en, 
            'Title_fr' => $request->Title_fr, 
            'color' => $request->color, 
        ]);
        return redirect()->route('Categories.index')

                        ->with('success','Categorias Store successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $slug
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        //To Get  Categorias 
        $Categorias = Categorias::where('slug', '=', $slug)->firstOrFail();
        return view('Dashboard.Categories.edit',compact('Categorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $slug)
    {
        // GET Post
        $Categorias = Categorias::where('slug', '=', $slug)->firstOrFail();
        // GET validate
        $data = $request->validate([
        'Title_ar' => 'required',
        'Title_en' => 'required',
        'Title_fr' => 'required',
        ]);
        $Categorias->parent_id = $request->input('parent_id');
        $Categorias->order = $request->input('order');
        $Categorias->Title_ar = $request->input('Title_ar');
        $Categorias->Title_en = $request->input('Title_en');
        $Categorias->Title_fr = $request->input('Title_fr');
        $Categorias->color = $request->input('color');
        $Categorias->save();
        return redirect()->route('Categories.index')

                        ->with('success','Categorias Updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Categorias Delete
        $Categorias = Categorias::findOrFail($id);
        $Categorias->delete();
        return back()->with('Delete','Categorias deleted successfully');
    }
}

app/Http/Controllers/Dashboard/Clients.php
<?php

namespace App\Http\Controllers\Dashboard;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreClient;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User; 
use App\Client;
use Auth;
use File;
use Validator;
use App\ImageUpload;

class Clients extends Controller
{


    /**
     * Show the middleware dashboard Super-Admin.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function __construct()
    {
        $this->middleware(['auth','role_or_permission:Super-Admin|edit articles']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // GET Clients
        $Clients = Client::simplePaginate(5);
        return view('Dashboard.Clients.index',compact('Clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // GET dashboardRoles create
        return view('Dashboard.Clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
             // GET validate
        $request->validate([
        'Title_ar' => 'required',
        'Title_en' => 'required',
        'Title_fr' => 'required',
        'body_ar' => 'required',
        'body_en' => 'required',
        'body_fr' => 'required'
        ]);

        $ImageUpload = ImageUpload::max('id');
        Client::create([  
            'Title_ar' => $request->Title_ar,  
            'Title_en' => $request->Title_en, 
            'Title_fr' => $request->Title_fr,
            'body_ar' => $request->body_ar,  
            'body_en' => $request->body_en,
            'body_fr' => $request->body_fr,
            'ImageUpload_id' => $ImageUpload
        ]);

            return redirect()->route('Clients.index')

                        ->with('success','Client Store successfully.');
    }

   /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $slug
     * @return \Illuminate\Http\Response
     */
    public function edit($Title_en)
    {
        //To Get All Client 
        $Client = Client::where('Title_en', '=', $Title_en)->firstOrFail();
        return view('Dashboard.Clients.edit',compact('Client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $Title_en
     * @return \Illuminate\Http\Response
     */
    
    public function update(Request $request, $Title_en)
    {
        // GET Client
        $Client = Client::where('Title_en', '=', $Title_en)->firstOrFail();
        $ImageOld = ImageUpload::max('id');
        if($ImageOld != $Client->ImageUpload_id) {
            $ClientImage = $Client->ImageUpload_id;
            $ClientImage = ImageUpload::findOrFail($ClientImage);
            File::delete($ClientImage->filename);
            $ClientImage->delete();
        }
        $request->validate([
        'Title_ar' => 'required',
        'Title_en' => 'required',
        'Title_fr' => 'required',
        'body_ar' => 'required',
        'body_en' => 'required',
        'body_fr' => 'required'
        ]);

        $Client->Title_ar = $request->input('Title_ar');
        $Client->Title_en = $request->input('Title_en');
        $Client->Title_fr = $request->input('Title_fr');
        $Client->body_ar = $request->input('body_ar');
        $Client->body_en = $request->input('body_en');
        $Client->body_fr = $request->input('body_fr');
        $Client->ImageUpload_id = $ImageOld;
        $Client->save();
        return redirect()->route('Clients.index')

                        ->with('success','Client Updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Client Delete
        $Client = Client::findOrFail($id);
        $ClientImage = $Client->ImageUpload_id;
        $ClientImage = ImageUpload::findOrFail($ClientImage);
        File::delete($ClientImage->filename);
        $ClientImage->delete();
        $Client->delete();
        return back()->with('Delete','Client deleted successfully');
    }
}

app/Http/Controllers/Dashboard/Dashboard.php
<?php

namespace App\Http\Controllers\Dashboard;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User;  
use Auth;
use Session;

class Dashboard extends Controller
{


    /**
     * Show the middleware dashboard Super-Admin.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function __construct()
    {
        $this->middleware(['auth','role_or_permission:Super-Admin|edit articles']);
    }
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('Dashboard.index');
    }

}

resources/views/Dashboard/Instagrams/create.blade.php
@extends('Dashboard.main')

@section('Dashboard')
<!-- START PAGE CONTENT -->
<div class="content ">
  <!-- START PAGE COVER -->
  <div class="jumbotron page-cover" data-pages="parallax">
    <div class=" container-fluid  container-fixed-lg">
      <div class="inner">
        <!-- START BREADCRUMB -->
        <ol class="breadcrumb">  
          <li class="breadcrumb-item"><a href="{{ url('admin') }}">{{ __('Dashboard')}}</a></li>
          <li class="breadcrumb-item"><a href="{{ route('Instagrams.index') }}">{{ __('Instagrams')}}</a></li>
          <li class="breadcrumb-item active">{{ __('Create Instagram')}}</li>
        </ol>
        <!-- END BREADCRUMB -->
        <div class="container-md-height">
          <div class="row">
            <!-- START card -->
            <div class="card card-transparent">
              <div class="card-body">
                <h3><i class="pg-ui"></i>{{ __('add Instagram')}} </h3>
              </div>
            </div>
            <!-- END card -->
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- END PAGE COVER -->
  <!-- START CONTAINER FLUID -->
  <div class=" container-fluid container-fixed-lg">
    <!-- START card -->
    <div class="row">
      <div class="col-lg-6">
        <!-- START card -->
        <div class="card card-default">
          <div class="card-header ">
            <div class="card-title">
              {{ __('Create your Instagram')}}
            </div>
          </div>
          @if ($errors->any())    
          <div class="pgn-wrapper top-inline" data-position="top">
            <div class="pgn push-on-sidebar-open pgn-bar">
              <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">{{ __('Close')}}</span></button>
                @foreach ($errors->all() as $error)
                {{ $error }}
                @endforeach
              </div>
            </div>
          </div>
          @endif
          <div class="card-body">
          <form action="{{ route('Instagrams.store') }}" method="POST"  role="form" enctype="multipart/form-data"> 
              @csrf
            <div class="form-group form-group-default required">
              <label for="Title_en">{{ __('Instagram Title')}}</label>
              <input type="text" class="form-control @error('Title_en') is-invalid @enderror" required="" placeholder="ex: Instagram English" id="Title_en" name="Title_en">
              @error('Title_en')
                <div class="alert alert-danger">{{ $message }}</div>
              @enderror 
            </div>
            <div class="form-group form-group-default required">
              <label for="Title_ar">{{ __('Instagram Title')}}</label>
              <input type="text" class="form-control @error('Title_ar') is-invalid @enderror" required="" placeholder="ex: Instagram arabic" id="Title_ar" name="Title_ar">
              @error('Title_ar')
                <div class="alert alert-danger">{{ $message }}</div>
              @enderror 
            </div>
            <div class="form-group form-group-default required">
              <label for="Title_fr">{{ __('Instagram Title')}}</label>
              <input type="text" class="form-control @error('Title_fr') is-invalid @enderror" required="" placeholder="ex: Instagram france" id="Title_fr" name="Title_fr">
              @error('Title_fr')
                <div class="alert alert-danger">{{ $message }}</div>
              @enderror 
            </div>
            <div class="form-group form-group-default required">
              <label for="body_en">{{ __('Instagram Content English')}}</label>
              <input type="text" class="form-control @error('body_en') is-invalid @enderror" required="" placeholder="ex:Content English" id="body_en" name="body_en">
              @error('body_en')
                <div class="alert alert-danger">{{ $message }}</div>
              @enderror 
            </div>
            <div class="form-group form-group-default required">
              <label for="body_ar">{{ __('Instagram Content Arabic')}}</label>
              <input type="text" class="form-control @error('body_ar') is-invalid @enderror" required="" placeholder="ex:Content arabic" id="body_ar" name="body_ar">
              @error('body_ar')
                <div class="alert alert-danger">{{ $message }}</div>
              @enderror 
            </div>
            <div class="form-group form-group-default required">
              <label for="body_fr">{{ __('Instagram Content France')}}</label>
              <input type="text" class="form-control @error('body_fr') is-invalid @enderror" required="" placeholder="ex:Content france" id="body_fr" name="body_fr">
              @error('body_fr')
                <div class="alert alert-danger">{{ $message }}</div>
              @enderror 
            </div>
           <button class="btn btn-success btn-cons btn-animated from-left fa fa-save pull-right" type="submit">
            <span>{{ __('save')}}</span>
          </button>
        </div>
      </div>
      </form>
      <!-- END card -->
    </div>
    <div class="col-lg-6">
      <!-- START card -->
      <div class="card card-default">
        <div class="card-header ">
          <div class="card-title">
            {{ __('Drag and drop Image Here')}}
          </div>
        </div>
        <div class="card-body no-scroll no-padding">
          <form method="post" action="{{url('Dashboard/image/upload/store')}}" enctype="multipart/form-data" class="dropzone" id="dropzone">
            @csrf
          </form> 
      </div>
    </div>
    <!-- END card -->
  </div>
</div>
<!-- END card -->
</div>
<!-- END CONTAINER FLUID -->
@endsection

resources/views/Dashboard/Instagrams/index.blade.php
@extends('Dashboard.main')

@section('Dashboard')
<!-- START PAGE CONTENT -->
<!-- ====================== links Roles Content Start =============================================== -->
  @if ($message = Session::get('success'))
  <div class="pgn-wrapper" data-position="top-right">
    <div class="pgn push-on-sidebar-open pgn-flip">
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">×</span>
          <span class="sr-only">{{ __('Close')}}</span>
        </button><span>{{ $message }}</span>
      </div>
    </div>
  </div>
  @endif 
  <!-- ====================== links Roles Content Start =============================================== -->
  @if ($message = Session::get('Delete'))
  <div class="pgn-wrapper" data-position="bottom-right">
    <div class="pgn push-on-sidebar-open pgn-flip">
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">×</span>
          <span class="sr-only">{{ __('Close')}}</span>
        </button><span>{{ $message }}</span>
      </div>
    </div>
  </div>
  @endif
  <!-- ====================== links Roles Content Start =============================================== -->
<div class="content ">
  <!-- START PAGE COVER -->
  <div class="jumbotron page-cover" data-pages="parallax">
    <div class=" container-fluid  container-fixed-lg">
      <div class="inner">
        <!-- START BREADCRUMB -->
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ url('admin') }}">{{ __('Dashboard')}}</a></li>
          <li class="breadcrumb-item active">{{ __('Instagrams')}}</li>
        </ol>
        <!-- END BREADCRUMB -->
        <div class="container-md-height">
          <div class="row">
            <!-- START card -->
            <div class="card card-transparent">
              <div class="card-body">
                <h3><i class=" pg-ui"></i> {{ __('Instagrams')}} <a href="{{ route('Instagrams.create') }}" class="btn btn-tag btn-success btn-tag-rounded">{{ __('Add Instagram')}} </a></h3>
              </div>
            </div>
            <!-- END card -->
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- END PAGE COVER -->
  <!-- START CONTAINER FLUID -->
  <div class=" container-fluid   container-fixed-lg bg-white">
    <!-- START card -->
    <div class="card card-transparent">
      <div class="card-header ">
        <div class="card-title">{{ __('Table Instagrams')}}
        </div>
        <div class="pull-right">
          <div class="col-xs-12">
            <input type="text" id="search-table" class="form-control pull-right" placeholder="Search">
          </div>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="card-body">
        <table class="table table-hover demo-table-search table-responsive-block" id="tableWithSearch">
          <thead>
            <tr>
              <th>{{ __('Image')}}</th>
              <th>{{ __('Tiltle')}}</th>
              <th>{{ __('Content')}}</th>
              <th class="text-right">{{ __('Actions')}}</th>
            </tr>
          </thead>
          <tbody>
            <!-- ================================ Instagrams Content Start ======================== -->
            @foreach($Instagrams as $Instagram)
            <tr>
              <td class="v-align-middle semi-bold">
                <span class="thumbnail-wrapper d48 circul2 inline">
                @if(isset($Instagram->ImageUpload->filename))
                 <img src="{{ asset($Instagram->ImageUpload->filename) }}" alt="{{ $Instagram->Title_en  }}" data-src="{{ asset($Instagram->ImageUpload->filename) }}" width="32" height="32">
                 @else
                 <td class="v-align-middle"><a class="btn btn-tag">{{ __('Images')}}</a></td>
                 <img alt="{{ $Instagram->Title_en  }}" width="32" height="32">
                 @endif
                </span>
              </td>
              <td class="v-align-middle semi-bold">
                <p>{{ $Instagram->Title_en  }}</p>
              </td>
              <td class="v-align-middle">{{ $Instagram->body_en  }}</td>
              <td class="v-align-middle text-right">
                <p>
                  <a href="{{ route('Instagrams.edit',$Instagram->Title_en) }}" class="btn btn-complete btn-cons btn-animated from-left fa fa-edit"><span>{{ __('Edit')}}</span></a>
                  <form action="{{ route('Instagrams.destroy',$Instagram->id) }}" method="POST" class="displayinline-block">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn btn-danger btn-cons btn-animated from-top fa  fa-remove">
                    <span>{{ __('Delete')}}</span>
                  </button>
                  </form>
                </p>
              </td>
            </tr>
            @endforeach
            <!-- ================================ Instagrams Content Start ======================== -->
          </tbody>
        </table>
        <!-- ====================== links Instagrams Content Start =============================================== -->
         {{ $Instagrams->links() }}
        <!-- ====================== links Instagrams Content Start =============================================== -->
      </div>
    </div>
    <!-- END card -->
  </div>
  <!-- END CONTAINER FLUID -->
</div>
<!-- END PAGE CONTENT -->
@endsection