routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| LaravelLocalization
|--------------------------------------------------------------------------
|
*/

Route::group([
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
function () {


	    Route::get('/', 'HomeController@index')->name('index');
        Route::get('search', 'SearchController@search')->name('search');
        Route::group(['middleware' => ['isVerified']], function () {
        	Route::get('email-verification/error', 'Auth\RegisterController@getVerificationError')->name('email-verification.error');
        	Route::get('email-verification/check/{token}', 'Auth\RegisterController@getVerification')->name('email-verification.check');
        });
        /*
        |--------------------------------------------------------------------------
        | Auth Routes
        |--------------------------------------------------------------------------
        |
        */
	    Auth::routes();
        /*
        |--------------------------------------------------------------------------
        | missing RETURN 404 PAGE Route
        |--------------------------------------------------------------------------
        |
        */
        Route::get('missing', function () {
        	return view('404');
        });
        /*
        |--------------------------------------------------------------------------
        | resource
        |--------------------------------------------------------------------------
        |
        */
		Route::resource('Cat','Categoriass');
		Route::get('/Peliculas/{slug}','Categoriass@ShowPelicula');
        Route::resource('Peliculass','Peliculas');
	     /**
	     * Show the middleware dashboard Super-Admin.
	     *
	     * @return \Illuminate\Contracts\Support\Renderable
	     */
	     Route::group(['middleware' => ['auth','role:Super-Admin']], function () {

		    /*
			|--------------------------------------------------------------------------
			| Web Routes Dashboard
			|--------------------------------------------------------------------------
			|
			| Here is where you can register web routes for your application. These
			| routes are loaded by the RouteServiceProvider within a group which
			| contains the "web" middleware group. Now create something great!
			|
			*/

		


			Route::resource('admin','Dashboard\Dashboard');
			Route::resource('Dashboard/Roles','Dashboard\Roles');
			Route::resource('Dashboard/Users','Dashboard\Users');
			Route::resource('Dashboard/AdSense','Dashboard\AdSenses');
			
			Route::resource('Dashboard/Clients','Dashboard\Clients');
			Route::resource('Dashboard/Galleries','Dashboard\Galleries');
			Route::resource('Dashboard/Instagrams','Dashboard\Instagrams');
			Route::resource('Dashboard/Links','Dashboard\Links');
			Route::resource('Dashboard/Menus','Dashboard\Menus');
			Route::resource('Dashboard/Media','Dashboard\Media');
			Route::resource('Dashboard/Messages','Dashboard\Messages');
			Route::resource('Dashboard/Posts','Dashboard\Posts');
			Route::resource('Dashboard/Seo','Dashboard\Seo');
			Route::resource('Dashboard/Settings','Dashboard\Settings');

		    });


});
Route::group(['middleware' => ['auth','role:Super-Admin']], function () {
Route::get('Dashboard/image/upload','ImageUploadController@fileCreate');
Route::post('Dashboard/image/upload/store','ImageUploadController@fileStore');
Route::post('Dashboard/image/delete','ImageUploadController@fileDestroy');
});

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\menu_item;

class Menu extends Model
{
     /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'Title'
    ];

    // THIS function menu_item TO MAKE RELATHION WITH menu
    public function menu_items()
    {
        return $this->hasMany(menu_item::class);
    }
}

app/Http/Controllers/Dashboard/AdSenses.php
<?php
namespace App\Http\Controllers\Dashboard;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreAdSense;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User; 
use App\AdSense;
use Auth; 
use File;
use Validator; 

class AdSenses extends Controller
{


    /**
     * Show the middleware dashboard Super-Admin.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function __construct()
    {
        $this->middleware(['auth','role_or_permission:Super-Admin|edit articles']);
    }
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          // GET AdSenses
          $AdSenses = AdSense::simplePaginate(5);
          return view('Dashboard.AdSense.index',compact('AdSenses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // GET AdSense create
        return view('Dashboard.AdSense.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
        'Location' => 'required|max:255',
        'name' => 'required|max:30',
        'Display' => 'required|max:30',
        'url' =>'required|unique:ad_senses|max:30',
        'code' => 'required|unique:ad_senses|max:200',
        ]);
        AdSense::create([
            'Location' => $request->Location,  
            'name' => $request->name,   
            'Display' => $request->Display,  
            'Type' => $request->Type, 
            'Active' => $request->Active, 
            'url' => $request->url,
            'code' => $request->code
        ]);
        return redirect()->route('AdSense.index')

                        ->with('success','AdSense Store successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $name
     * @return \Illuminate\Http\Response
     */
    public function edit($name)
    {
        //To Get AdSense 
        $AdSense = AdSense::where('name', '=', $name)->firstOrFail();
        return view('Dashboard.AdSense.edit',compact('AdSense'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $name)
    {
        // GET AdSense
        $AdSense = AdSense::where('name', '=', $name)->firstOrFail();
        // GET validate
        $data = $request->validate([
        'Location' => 'required|max:255',
        'name' => 'required|max:30',
        'Display' => 'required|max:30',
        'url' =>'required|unique:ad_senses|max:30',
        'code' => 'required|unique:ad_senses|max:200',
        ]);
        $AdSense->Location  = $request->input('Location');
        $AdSense->name = $request->input('name');
        $AdSense->Display = $request->input('Display');
        $AdSense->Type = $request->input('Type');
        $AdSense->Active = $request->input('Active');
        $AdSense->url = $request->input('url');
        $AdSense->code = $request->input('code');
        $AdSense->save();
        return redirect()->route('AdSense.index')

                        ->with('success','AdSense Updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         // AdSense AdSense
        $AdSense = AdSense::findOrFail($id);
        $AdSense->delete();
        return back()->with('Delete','AdSense deleted successfully');
    }
}

app/Http/Controllers/Dashboard/Categories.php
<?php

namespace App\Http\Controllers\Dashboard;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCategorias;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User; 
use App\Categorias;
use Auth;
use File;
use Validator;  
  
class Categories extends Controller
{


    /**
     * Show the middleware dashboard Super-Admin.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function __construct()
    {
        $this->middleware(['auth','role_or_permission:Super-Admin|edit articles']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          // GET Categories
          $Categories = Categorias::simplePaginate(5);
          return view('Dashboard.Categories.index',compact('Categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // GET Categories create
        return view('Dashboard.Categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
        'parent_id' => 'required|max:255',
        'order' => 'required',
        'Title_ar' => 'required',
        'Title_en' => 'required',
        'Title_fr' => 'required',
        'color' => 'required',
        ]);

        Categorias::create([
            'parent_id' => $request->parent_id,  
            'order' => $request->order,   
            'Title_ar' => $request->Title_ar,  
            'Title_en' => $request->Title_en, 
            'Title_fr' => $request->Title_fr, 
            'color' => $request->color, 
        ]);
        return redirect()->route('Categories.index')

                        ->with('success','Categorias Store successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $slug
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        //To Get  Categorias 
        $Categorias = Categorias::where('slug', '=', $slug)->firstOrFail();
        return view('Dashboard.Categories.edit',compact('Categorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $slug)
    {
        // GET Post
        $Categorias = Categorias::where('slug', '=', $slug)->firstOrFail();
        // GET validate
        $data = $request->validate([
        'Title_ar' => 'required',
        'Title_en' => 'required',
        'Title_fr' => 'required',
        ]);
        $Categorias->parent_id = $request->input('parent_id');
        $Categorias->order = $request->input('order');
        $Categorias->Title_ar = $request->input('Title_ar');
        $Categorias->Title_en = $request->input('Title_en');
        $Categorias->Title_fr = $request->input('Title_fr');
        $Categorias->color = $request->input('color');
        $Categorias->save();
        return redirect()->route('Categories.index')

                        ->with('success','Categorias Updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Categorias Delete
        $Categorias = Categorias::findOrFail($id);
        $Categorias->delete();
        return back()->with('Delete','Categorias deleted successfully');
    }
}

app/Http/Controllers/Dashboard/Clients.php
<?php

namespace App\Http\Controllers\Dashboard;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreClient;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User; 
use App\Client;
use Auth;
use File;
use Validator;
use App\ImageUpload;

class Clients extends Controller
{


    /**
     * Show the middleware dashboard Super-Admin.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function __construct()
    {
        $this->middleware(['auth','role_or_permission:Super-Admin|edit articles']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // GET Clients
        $Clients = Client::simplePaginate(5);
        return view('Dashboard.Clients.index',compact('Clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // GET dashboardRoles create
        return view('Dashboard.Clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
             // GET validate
        $request->validate([
        'Title_ar' => 'required',
        'Title_en' => 'required',
        'Title_fr' => 'required',
        'body_ar' => 'required',
        'body_en' => 'required',
        'body_fr' => 'required'
        ]);

        $ImageUpload = ImageUpload::max('id');
        Client::create([  
            'Title_ar' => $request->Title_ar,  
            'Title_en' => $request->Title_en, 
            'Title_fr' => $request->Title_fr,
            'body_ar' => $request->body_ar,  
            'body_en' => $request->body_en,
            'body_fr' => $request->body_fr,
            'ImageUpload_id' => $ImageUpload
        ]);

            return redirect()->route('Clients.index')

                        ->with('success','Client Store successfully.');
    }

   /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $slug
     * @return \Illuminate\Http\Response
     */
    public function edit($Title_en)
    {
        //To Get All Client 
        $Client = Client::where('Title_en', '=', $Title_en)->firstOrFail();
        return view('Dashboard.Clients.edit',compact('Client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $Title_en
     * @return \Illuminate\Http\Response
     */
    
    public function update(Request $request, $Title_en)
    {
        // GET Client
        $Client = Client::where('Title_en', '=', $Title_en)->firstOrFail();
        $ImageOld = ImageUpload::max('id');
        if($ImageOld != $Client->ImageUpload_id) {
            $ClientImage = $Client->ImageUpload_id;
            $ClientImage = ImageUpload::findOrFail($ClientImage);
            File::delete($ClientImage->filename);
            $ClientImage->delete();
        }
        $request->validate([
        'Title_ar' => 'required',
        'Title_en' => 'required',
        'Title_fr' => 'required',
        'body_ar' => 'required',
        'body_en' => 'required',
        'body_fr' => 'required'
        ]);

        $Client->Title_ar = $request->input('Title_ar');
        $Client->Title_en = $request->input('Title_en');
        $Client->Title_fr = $request->input('Title_fr');
        $Client->body_ar = $request->input('body_ar');
        $Client->body_en = $request->input('body_en');
        $Client->body_fr = $request->input('body_fr');
        $Client->ImageUpload_id = $ImageOld;
        $Client->save();
        return redirect()->route('Clients.index')

                        ->with('success','Client Updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Client Delete
        $Client = Client::findOrFail($id);
        $ClientImage = $Client->ImageUpload_id;
        $ClientImage = ImageUpload::findOrFail($ClientImage);
        File::delete($ClientImage->filename);
        $ClientImage->delete();
        $Client->delete();
        return back()->with('Delete','Client deleted successfully');
    }
}

app/Http/Controllers/Dashboard/Dashboard.php
<?php

namespace App\Http\Controllers\Dashboard;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User;  
use Auth;
use Session;

class Dashboard extends Controller
{


    /**
     * Show the middleware dashboard Super-Admin.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function __construct()
    {
        $this->middleware(['auth','role_or_permission:Super-Admin|edit articles']);
    }
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('Dashboard.index');
    }

}

resources/views/Dashboard/Menus/create.blade.php
@extends('Dashboard.main')

@section('Dashboard')
@endsection

resources/views/Dashboard/Menus/index.blade.php
@extends('Dashboard.main')

@section('Dashboard')
<!-- START PAGE CONTENT -->
<!-- ====================== links Roles Content Start =============================================== -->
  @if ($message = Session::get('success'))
  <div class="pgn-wrapper" data-position="top-right">
    <div class="pgn push-on-sidebar-open pgn-flip">
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">×</span>
          <span class="sr-only">{{ __('Close')}}</span>
        </button><span>{{ $message }}</span>
      </div>
    </div>
  </div>
  @endif 
  <!-- ====================== links Roles Content Start =============================================== -->
  @if ($message = Session::get('Delete'))
  <div class="pgn-wrapper" data-position="bottom-right">
    <div class="pgn push-on-sidebar-open pgn-flip">
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">×</span>
          <span class="sr-only">{{ __('Close')}}</span>
        </button><span>{{ $message }}</span>
      </div>
    </div>
  </div>
  @endif
  <!-- ====================== links Roles Content Start =============================================== -->
<div class="content p-b-100">
  <!-- START PAGE COVER -->
  <div class="jumbotron page-cover" data-pages="parallax">
    <div class=" container-fluid  container-fixed-lg">
      <div class="inner">
        <!-- START BREADCRUMB -->
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ url('admin') }}">{{ __('Dashboard')}}</a></li>
          <li class="breadcrumb-item active">{{ __('Menus')}}</li>
        </ol>  
        <!-- END BREADCRUMB -->
        <div class="container-md-height">
          <div class="row">
            <!-- START card -->
            <div class="card card-transparent">
              <div class="card-body">
                <h3><i class="pg-menu"></i> {{ __('Menus')}} 
                  <button class="btn btn-tag btn-success btn-tag-rounded" data-target="#modalFillIn" data-toggle="modal" id="btnFillSizeToggler2">{{ __('Add Menu')}}</button>
                </h3>
              </div>
            </div>
            <!-- END card -->
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Modal -->
  <!-- START CONTAINER FLUID -->
  <div class="container-fluid  container-fixed-lg bg-white">
      <!-- Modal -->
      <div class="modal fade fill-in" id="modalFillIn" tabindex="-1" role="dialog" aria-hidden="true">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          <i class="pg-close"></i>
        </button>
        <div class="modal-dialog ">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="text-left p-b-5"><span class="semi-bold">{{ __('Create Menu')}} </h5>
              </div>
              <div class="modal-body">
                <div class="row">
                  <form action="{{ route('Menus.store') }}" method="POST"  role="form" enctype="multipart/form-data" class="display-inherit"> 
                  @csrf
                  <div class="col-lg-9">
                    <input type="text" placeholder="Your Menu Title" class="form-control input-lg" id="icon-filter" name="Title">
                  </div>
                  <div class="col-lg-3 no-padding sm-m-t-10 sm-text-center">
                    <button type="submit" class="btn btn-primary btn-lg btn-large fs-15">{{ __('Create')}}</button>
                  </div>
                  </form>
                </div>
              </div>
              <div class="modal-footer">
              </div>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
        </div>
        <!-- Modal -->
        <!-- MODAL STICK UP  -->
        <div class="modal fade stick-up" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header clearfix text-left">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
                </button>
                <h5>{{ __('Item Menu')}}</h5>
                <p>{{ __('You can output this Item Menu anywhere')}}</p>
              </div>
              <div class="modal-body">
                  <form action="{{ route('Links.store') }}" method="POST"  role="form" enctype="multipart/form-data" class="display-inherit"> 
                  @csrf
                  <div class="form-group-attached">
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group form-group-default">
                          <label for="Title_en">{{ __('Title Item Menu English')}}</label>
                          <input type="text" class="form-control" name="Title_en">
                        </div>
                      </div>
                    </div>
                     <div class="row">
                      <div class="col-md-12">
                        <div class="form-group form-group-default">
                          <label for="Title_ar">{{ __('Title Item Menu Arabic')}}</label>
                          <input type="text" class="form-control" name="Title_ar">
                        </div>
                      </div>
                    </div>
                     <div class="row">
                      <div class="col-md-12">
                        <div class="form-group form-group-default">
                          <label for="Title_fr">{{ __('Title Item Menu France')}}</label>
                          <input type="text" class="form-control" name="Title_fr">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group form-group-default">
                          <label>{{ __('Url Item Menu www.example.com/Category')}}</label>
                          <input type="text" class="form-control" name="url">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group form-group-default">
                          <label>{{ __('Order Item Number')}}</label>
                          <input type="number" class="form-control" name="order">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                     <div class="form-group form-group-default">
                      <label>{{ __('Target Item Menu')}} </label>
                      <select class="full-width border-zero"  name="target">
                        <option value="_blank" selected="">{{ __('Item Menu Target')}}</option>
                        <option value="_blank">{{ __('_blank')}}</option>
                        <option value="_self">{{ __('_self')}}</option>
                        <option value="_parent">{{ __('_parent')}}</option>
                        <option value="_top">{{ __('_top')}}</option>
                      </select>
                    </div>
                  </div>
                   <div class="row">
                     <div class="form-group form-group-default">
                      <label>{{ __('Menu')}}</label>
                        <select class="full-width border-zero" name="menu_id">
                        <!-- ================================ Menus Content Start ======================== -->
                        @foreach($Menus as $Menu)
                         <option value="{{ $Menu->id }}" selected="">{{ $Menu->Title }}</option>
                        @endforeach
                        <!-- ================================ Menus Content Start ======================== -->
                      </select>
                    </div>
                  </div>
                </div>
              <div class="row">
                <div class="col-md-4 m-t-10 sm-m-t-10">
                  <button type="submit" class="btn btn-primary btn-block m-t-5">{{ __('Item Menu')}}</button>
                </div>
              </div>
              </form>
            </div>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- END MODAL STICK UP  -->
    <div class="row">
      <div class="col-lg-12">
        <div class="card card-default bg-success mt20">
          <div class="card-header  separator">
            <div class="card-title">{{ __('Menu Builder Static')}}
            </div>
          </div>
          <div class="card-body">
            <p class="text-black hint-text">{{ __('You can output this Menu anywhere on your site by calling Foreach Menus as Menu ')}}</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="card card-borderless">
          <ul class="nav nav-tabs nav-tabs-simple" role="tablist" data-init-reponsive-tabs="dropdownfx">
            <li class="nav-item">
              <a class="active" data-toggle="tab" role="tab" data-target="#MenuBuilder" href="#">{{ __('Menu Builder')}}</a>
            </li>
            <!-- ================================ Menus Content Start ======================== -->
            @foreach($Menus as $Menu)
            <li class="nav-item">
              <a href="#" data-toggle="tab" role="tab" data-target="#{{ $Menu->id }}">{{ $Menu->Title }}</a>
            </li>
            @endforeach
            <!-- ================================ Menus Content Start ======================== -->
          </ul> 
          <div class="tab-content">
            <div class="tab-pane active" id="MenuBuilder">
              <div class="row column-seperation">
                <div class="col-lg-6">
                  <h3>
                   {{ __('Menu Builder Static')}}  <button class="btn btn-complete btn-cons" id="btnStickUpSizeToggler">{{ __('Item Menu')}}</button>
                    <p>
                      {{ __('You can output this Menu anywhere on your site by calling Foreach Menus as Menu')}}
                    </p>
                  </h3>
                </div>
              </div>
            </div>
            <!-- ================================ Menus Content Start ======================== -->
            @foreach($Menus as $Menu)
            <div class="tab-pane" id="{{ $Menu->id }}">
              <div class="row">
                <div class="col-lg-12">
                  <h3>{{ $Menu->Title }} <form action="{{ route('Menus.destroy',$Menu->id) }}" method="POST" class="displayinline-block">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn btn-danger btn-cons btn-animated from-top fa  fa-remove">
                    <span>{{ __('Delete')}}</span>
                  </button>
                  </form>
                </h3>
                  <p>{{ __('You can output this menu anywhere on your site by calling Edit your Menu in Helper File')}}</p>
                  <br>
                    <!-- ====================== links Menu Content Start store =============================================== -->
                    @foreach($Menu->menu_items as $item)  
                   <div id="card-circular-color" class="card card-default">
                    <div class="card-header">
                      <div class="card-title">{{ __('Target Item Menu')}} ({{ $item->target }})
                      </div>
                      <div class="card-controls">
                      <div class="btn-group btn-group-sm">
                      <form action="{{ route('Links.destroy',$item->id) }}" method="POST" class="displayinline-block">
                      @csrf
                      @method('DELETE')
                      <button class="btn btn-danger btn-cons"  type="submit">{{ __('Delete')}}</button>
                      </form>   
                      </div>
                      </div>
                    </div>
                    <div class="card-body">
                      <h3>
                      {{ $item->Title_en }}</h3>
                      <p>{{ __('Url Item Menu')}} (<a href="{{ url('')}}/{{ $item->url }}" target="_blank">{{ $item->url }}</a>) {{ __('& Order Item Number')}} ({{ $item->order }})
                      </p>
                    </div>
                   </div>
                   @endforeach
                   <!-- ================================ Menus Content Start ======================== -->
                  <p class="pull-right">
                    <button type="button" class="btn btn-success btn-cons">{{ __('Save Changes')}}</button>
                  </p>
                </div>
              </div>
            </div>
            @endforeach
            <!-- ================================ Menus Content Start ======================== -->
            <div class="tab-pane" id="tab2Inspire">
              <div class="row">
                <div class="col-lg-12">
                  <h3>{{ __('Follow us')}} &amp; {{ __('get updated!')}}</h3>
                  <p>{{ __('Instantly connect to whats most important to you. Follow your friends, experts, favorite celebrities, and breaking news.')}}</p>
                  <br>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    </div>
  <!-- END CONTAINER FLUID -->
  @endsection